### ISSUE TITLE
A question about pixel decoder

### ISSUE THREAD

**Issue by LiJiahang617** [facebookresearch/Mask2Former#205]
Your work is excellent and impressive!
But I have a little question about your pixel decoder design:
In your paper, you mentioned“use a simple upsampling layer with lateral connection on the final 1/8 feature map to generate the feature map of resolution 1/4 as the per-pixel embedding”
In the code, it's a FPN-like structure with only one upsample opt, have you tried to use all 4-layer features to do this opt?
I mean if it will get a better mask feature by fusing all stages features instead of only 2 layers feature? Have you conducted such experiments?
Thanks again for your great work!

**Comment by bowenc0221** [comment]
Hi @LiJiahang617, the description in the paper corresponds to the pixel decoder with MSDeformable Attention. We used 3 scales (1/32, 1/16/, 1/8) in the MSDeformable Attention and the final output is upsampling the 1/8 features and adding to the 1/4 features from the backbone. I haven't tried adding features from 1/32 and 1/16 since they are already mixed in the generation of 1/8 features due to MSDeformable Attention.

**Comment by LiJiahang617** [comment]
Thanks for your reply! It helps me a lot, and allows me to express my admiration to you once again for this excellent work!
