### ISSUE TITLE
About the performance in Table XId

### ISSUE THREAD

**Issue by zen-star** [facebookresearch/Mask2Former#72]
Thanks for the excellent work.  

I know the only difference between the two results (AP:37.8 vs 41.5; PQ:48.2 vs 50.7) in Table XId is the transformer decoder, but what is the difference between the second line and the third line in Table 1 (AP:41.5 vs 41.7; PQ:50.7 vs 51.9)? Is it about the pixel decoder?

Look forward to your reply^^

**Comment by zen-star** [comment]
Sorry, I must correct my words: "but what is the difference between the second line **in the Table XId** and the third line in Table 1 (AP:41.5 vs 41.7; PQ:50.7 vs 51.9)?"

**Comment by bowenc0221** [comment]
In Table XId: (1) the pixel decoder is FPN instead of MSDeformAttn; (2) AP is the model trained on instance segmentation and PQ is the model trained on panoptic segmentation.

In Table 1: (1) pixel decoder is MSDeformAttn; (2) AP is the model trained on panoptic segmentation and we only take the 80 thing category to evaluate instance segmentation.

**Comment by zen-star** [comment]
I see...
The stronger pixel decoder matters a lot, and I should refer to Table 4(a) for fair comparison about different pixel decoders and Table 7 for AP gap between panoptic segmentation and only instance segmentation.
Am I right?
