### ISSUE TITLE
Question about the length of training time

### ISSUE THREAD

**Issue by OliviaWang123456** [facebookresearch/Mask2Former#9]
Hello, thank you for timely sharing the source code.
But I found that the training speed was very slow on my server. 
Could u plz tell me the length of your training time on 8 V100?

configs/coco/instance-segmentation/maskformer2_R50_bs16_50ep.yaml
configs/coco/instance-segmentation/maskformer2_R101_bs16_50ep.yaml

**Comment by bowenc0221** [comment]
The training time of ResNet-50 backbone is around 3 days on 8 V100 GPUs for 50 epochs.

There are few ways to reduce training time:
1. Using FPN decoder instead of MSDeformAttn: we found MSDeoformAttn is much slower than FPN decoder, probably due to suboptimal CUDA implementation
2. Using fewer decoder layers: e.g., using 6 or even 3 layers
3. Using a shorter training schedule: you can check our paper appendix to see results of 12 and 25 epochs

But keep in mind that all these modifications sacrifice accuracy for speed.
